# # # App Settings # # #
MAX_USERS = 10
MAX_JOBS = 5

# # # Main Navigation Links # # #
RETURN = "0"

# Sign-In Menu #
LOGIN_SIGN_IN = "11"
LOGIN_CREATE_ACCOUNT = "12"
LOGIN_SEARCH = "13"
LOGIN_JOIN = "14"
LOGIN_EXIT = "15"

# Main Menu #
MAIN_SKILL = "11"
MAIN_CONNECTIONS = "12"
MAIN_JOBS = "13"
MAIN_NETWORK = "14"
MAIN_EXIT = "15"

# Useful Links #
USEFUL_GENERAL = "21"
USEFUL_BROWSE = "22"
USEFUL_BUSINESS = "23"
USEFUL_DIRECTORIES = "24"

# Important Links #
IMPORTANT_COPYRIGHT_NOTICE = "31"
IMPORTANT_ABOUT = "32"
IMPORTANT_ACCESS = "33"
IMPORTANT_USER_AGREEMENT = "34"
IMPORTANT_COOKIE = "35"
IMPORTANT_COPYRIGHT_POLICY = "36"
IMPORTANT_BRAND = "37"
IMPORTANT_PRIVACY = "38"
IMPORTANT_LANGUAGE = "39"

# General Links #
GENERAL_SIGN_UP = "1"
GENERAL_HELP = "2"
GENERAL_ABOUT = "3"
GENERAL_PRESS = "4"
GENERAL_BLOG = "5"
GENERAL_CAREERS = "6"
GENERAL_DEVELOPERS = "7"
